name: Carolla Show Data Archive

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write

jobs:
  build-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch and Process Podcast Data
        run: |
          curl -L -sS 'https://rss.art19.com/adam-carolla-show' -o carolla_rss.xml
          grep -E '<title>|<pubDate>' carolla_rss.xml > carolla_index.txt

      - name: Commit and Push to Repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add carolla_rss.xml carolla_index.txt
          
          # This check prevents "Exit Code 1" if the files haven't changed
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Database Sync: $(date +'%Y-%m-%d %H:%M')"
            git push
          fi
